# Generated by Django 5.1.2 on 2026-04-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='h_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='profile_urls',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='professor',
            name='recent_papers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='professor',
            name='research_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='professor',
            name='total_citations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='university',
            field=models.CharField(default='Unknown University', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='professor',
            constraint=models.UniqueConstraint(fields=('full_name', 'university'), name='unique_professor_name_university'),
        ),
    ]
