# Generated by Django 5.1.2 on 2026-04-24 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_professor_department_professor_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerpApiRawResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(db_index=True, max_length=128)),
                ('step', models.CharField(choices=[('search', 'Google Scholar Search'), ('author', 'Google Scholar Author')], max_length=16)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='professor',
            name='unique_professor_name_university',
        ),
        migrations.AddField(
            model_name='professor',
            name='author_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='citations_since_2021',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='h_index_since_2021',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='i10_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='i10_index_since_2021',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='last_enriched_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='professor',
            name='profile_picture_url',
            field=models.URLField(blank=True),
        ),
    ]
